### ISSUE TITLE
Importing the module v1.1.0 gives a js error

### ISSUE THREAD

**Issue by g2timo** [WegenenVerkeer/ng-kaart#1]
When I import the module version 1.1.0, I get following js error.

![image](https://user-images.githubusercontent.com/19432469/34100025-77ab75a4-e3e1-11e7-96e2-b1c69285dba9.png)

`imports: [
    KaartModule.withDefaults()
  ]`

**Comment by bepremeg** [comment]
Ja. Dat is bekend. Ik krijg het niet direct opgelost.

Ik heb wel een oplossing met een volledige repackaging van de component met

**Comment by bepremeg** [comment]
Zoals je misschien zelf al gezien hebt werkt versie 1.0.6 wel. Enig verschil is dat die afhangt van Angular 4.

**Comment by bepremeg** [comment]
Zou moeten werken in v1.1.1
